services:
  - type: web
    name: universal-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1