# Cloudflare Workers configuration for Universal MCP Server
name = "universal-mcp-server"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
# GOOGLE_API_KEY = "your-google-api-key-here"

# Custom domains (configure in Cloudflare dashboard)
[env.production]
routes = [
  { pattern = "api.yourdomain.com/*", custom_domain = true }
]

# Development environment
[env.development.vars]
# GOOGLE_API_KEY = "your-dev-google-api-key-here"

# Worker settings
[build]
command = ""

# Limits and performance
[limits]
cpu_ms = 50000

# KV namespaces (for future caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"