
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const ContentGeneratorPage = lazy(() => import("./pages/ContentGeneratorPage.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const SettingsPage = lazy(() => import("./pages/SettingsPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/content-generator-page", element: <ContentGeneratorPage />},
	{ path: "/contentgeneratorpage", element: <ContentGeneratorPage />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <Logout />},
	{ path: "/settings-page", element: <SettingsPage />},
	{ path: "/settingspage", element: <SettingsPage />},

];
